weights: ./WIDERface_landmarks/facemaster_hyp&anc/weights/last.pt
cfg: ''
data: data/widerface_w_landmarks.yaml
hyp: data/hyps/hyp.widerface_test.yaml
epochs: 300
batch_size: 32
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: '1'
multi_scale: false
single_cls: true
adam: false
sync_bn: false
workers: 8
project: WIDERface_landmarks
entity: null
name: facemaster_hyp&anc
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: WIDERface_landmarks/facemaster_hyp&anc
